### ISSUE TITLE
OAUTH_AUTHORIZE_VIEW ...... fake authorize view

### ISSUE THREAD

**Issue by Lohitha3** [philipforget/django-oauth-plus#1]
Hello,
I am getting the fakeauthorize view message when the authorization is done.What to set for the OAUTH_AUTHORIZE_VIEW in settings? I have an authorization template and the all but ending up getting that message. Could you please help with this.
Thankyou

**Comment by philipforget** [comment]
Hey there,

you likely want to point your question to the upstream repo: https://bitbucket.org/david/django-oauth-plus/wiki/Home

Although at this point, both of these repos are very old, and this fork in particular is not only unmaintained, but I barely recall what it's meant to even address. Best of luck!
